/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSoalRouteImport } from './routes/app.soal'
import { Route as AppRppRouteImport } from './routes/app.rpp'
import { Route as AppRkpRouteImport } from './routes/app.rkp'
import { Route as AppRiwayatRouteImport } from './routes/app.riwayat'
import { Route as AppRiwayatIdRouteImport } from './routes/app.riwayat.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSoalRoute = AppSoalRouteImport.update({
  id: '/soal',
  path: '/soal',
  getParentRoute: () => AppRoute,
} as any)
const AppRppRoute = AppRppRouteImport.update({
  id: '/rpp',
  path: '/rpp',
  getParentRoute: () => AppRoute,
} as any)
const AppRkpRoute = AppRkpRouteImport.update({
  id: '/rkp',
  path: '/rkp',
  getParentRoute: () => AppRoute,
} as any)
const AppRiwayatRoute = AppRiwayatRouteImport.update({
  id: '/riwayat',
  path: '/riwayat',
  getParentRoute: () => AppRoute,
} as any)
const AppRiwayatIdRoute = AppRiwayatIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppRiwayatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/riwayat': typeof AppRiwayatRouteWithChildren
  '/app/rkp': typeof AppRkpRoute
  '/app/rpp': typeof AppRppRoute
  '/app/soal': typeof AppSoalRoute
  '/app/': typeof AppIndexRoute
  '/app/riwayat/$id': typeof AppRiwayatIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/riwayat': typeof AppRiwayatRouteWithChildren
  '/app/rkp': typeof AppRkpRoute
  '/app/rpp': typeof AppRppRoute
  '/app/soal': typeof AppSoalRoute
  '/app': typeof AppIndexRoute
  '/app/riwayat/$id': typeof AppRiwayatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/riwayat': typeof AppRiwayatRouteWithChildren
  '/app/rkp': typeof AppRkpRoute
  '/app/rpp': typeof AppRppRoute
  '/app/soal': typeof AppSoalRoute
  '/app/': typeof AppIndexRoute
  '/app/riwayat/$id': typeof AppRiwayatIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/riwayat'
    | '/app/rkp'
    | '/app/rpp'
    | '/app/soal'
    | '/app/'
    | '/app/riwayat/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/riwayat'
    | '/app/rkp'
    | '/app/rpp'
    | '/app/soal'
    | '/app'
    | '/app/riwayat/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/riwayat'
    | '/app/rkp'
    | '/app/rpp'
    | '/app/soal'
    | '/app/'
    | '/app/riwayat/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/soal': {
      id: '/app/soal'
      path: '/soal'
      fullPath: '/app/soal'
      preLoaderRoute: typeof AppSoalRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rpp': {
      id: '/app/rpp'
      path: '/rpp'
      fullPath: '/app/rpp'
      preLoaderRoute: typeof AppRppRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rkp': {
      id: '/app/rkp'
      path: '/rkp'
      fullPath: '/app/rkp'
      preLoaderRoute: typeof AppRkpRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/riwayat': {
      id: '/app/riwayat'
      path: '/riwayat'
      fullPath: '/app/riwayat'
      preLoaderRoute: typeof AppRiwayatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/riwayat/$id': {
      id: '/app/riwayat/$id'
      path: '/$id'
      fullPath: '/app/riwayat/$id'
      preLoaderRoute: typeof AppRiwayatIdRouteImport
      parentRoute: typeof AppRiwayatRoute
    }
  }
}

interface AppRiwayatRouteChildren {
  AppRiwayatIdRoute: typeof AppRiwayatIdRoute
}

const AppRiwayatRouteChildren: AppRiwayatRouteChildren = {
  AppRiwayatIdRoute: AppRiwayatIdRoute,
}

const AppRiwayatRouteWithChildren = AppRiwayatRoute._addFileChildren(
  AppRiwayatRouteChildren,
)

interface AppRouteChildren {
  AppRiwayatRoute: typeof AppRiwayatRouteWithChildren
  AppRkpRoute: typeof AppRkpRoute
  AppRppRoute: typeof AppRppRoute
  AppSoalRoute: typeof AppSoalRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppRiwayatRoute: AppRiwayatRouteWithChildren,
  AppRkpRoute: AppRkpRoute,
  AppRppRoute: AppRppRoute,
  AppSoalRoute: AppSoalRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
